  - name: pre-commit
  # You may pin to the exact commit or the version.
  uses: pre-commit/action@v3.0.1
  with:
    # options to pass to pre-commit run
    extra_args: # optional, default is --all-files
          
